version: '3.8'

services:
  backend-server:
    build: .
    container_name: backend-server
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy    
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3308:3306"
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
      
networks:
  backend-network: {}