version: '3.8'

services:
  backend-server:
    build: .
    container_name: backend-server
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules 
    networks:
      - backend-network

networks:
  backend-network: {}